// <auto-generated />
namespace MyAbilityFirst.Infrastructure.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddCareWorkerSearchView : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCareWorkerSearchView));
        
        string IMigrationMetadata.Id
        {
            get { return "201705110206113_AddCareWorkerSearchView"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
